apiVersion: apps/v1
kind: Deployment
metadata:
  name: yandex-rasp-kt
  namespace: dev
  labels:
    app: yandex-rasp-kt
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  replicas: 2
  selector:
    matchLabels:
      app: yandexrasp
  template:
    metadata:
      labels:
        app: yandexrasp
    spec:
      volumes:
        - name: init-data
          hostPath:
            path: /volume/init_db.sql
            type: File
      containers:
        - name: yandexrasp
          imagePullPolicy: IfNotPresent
          image: docker.io/library/yandex-rasp-kt
          ports:
            - containerPort: 8080
          env:
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: postgres
            - name: DB_URL
              value: postgres-service.dev:15432
          volumeMounts:
            - name: init-data
              mountPath: /volume/init_db.sql
              subPath: init_db.sql