apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: postgres-service
  labels:
    app: postgres
spec:
  ports:
    - port: 15432
      targetPort: 5432
      protocol: TCP
  selector:
    app: postgres